version: "3.8"

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:latest
    container_name: django_cont
    ports:
      - "8001:8001"
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8001"
