version: "3.8"

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_app:latest
    container_name: django_cont
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw
    volumes:
      - .:/app  # Optional: useful for live reload during development

networks:
  notes-app-nw:
